import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }){
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      > <SidebarProvider>
        <AppSidebar />
        <main className="w-full">
         
          {children}
        </main>
      </SidebarProvider>

        
      </body>
    </html>
  );
}
